dist: xenial
language: python
sudo: false
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8-dev'
- 'nightly'
env:
- PYTHONPATH=.
install:
- pip install coveralls
script: coverage run ipgroup_test.py
after_success: coveralls
deploy:
  provider: pypi
  user: rypeck
  password:
    secure: ITMC3cQXglwDp8jvQxyduOwWdHtu5lT5YSuSkw1AwD4LxnWcH+sgnOM6+USAjS9ug43DvzuRHZ6v3auMcZ2tKwWLceaahSHzIsZOcUe5mPp/fXCqkxwLnT+W++LsBCQUajo6aGIReKOo+q9CdQcSzpyCvgo8xLNX/syXwPkrHJ4=
  on:
    branch: master
    tags: true
    python: 3.6
    repo: RyPeck/python-ipgroup
